[versions]

activity = "1.5.0-alpha01"
kotlinxSerialization = "1.3.3"
coroutines = "1.6.2"
koin = "3.1.5"
sqldelight = "1.5.0"
decompose = "0.6.0-native-compose-01"
reaktive = "1.1.22"
mviKotlin = "3.0.0-beta02"
ktor = "2.0.2"
compose = "1.2.0-beta02"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

decompose-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extension-compose = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
reaktive = { module = "com.badoo.reaktive:reaktive", version.ref = "reaktive" }

mviKotlin-mviKotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mviKotlin" }
mviKotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mviKotlin" }
mviKotlin-extensionReaktive = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-reaktive", version.ref = "mviKotlin" }
mviKotlin-extensionCoroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mviKotlin" }
mviKotlin-rx = { module = "com.arkivanov.mvikotlin:rx", version.ref = "mviKotlin" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref= "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor"}

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose"}
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose"}
compose-material = { module = "androidx.compose.material:material", version.ref = "compose"}
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose"}

[bundles]

ktor = [
    "ktor-core",
    "ktor-logging",
    "ktor-serialization",
    "ktor-negotiation"
]

mviKotlin = [
    "mviKotlin-mviKotlin",
    "mviKotlin-main",
    "mviKotlin-extensionCoroutines"
]

compose = [
    "compose-ui",
    "compose-foundation",
    "compose-material",
    "compose-runtime"
]